### ISSUE TITLE
Evaluate if is necessary use more sensors at wheels.

### ISSUE THREAD

**Issue by MichaelACosta** [UFPelRobotics/light-sensor#2]
Its necessary fix the sensors in robot for minimize the error between counter, if be necessary, add more one sensor for each wheel and use Kalman filter to estimate the counter value.

**Comment by WKolodziejski** [comment]
There's a huge difference between the values of each wheel.
In a test done today, the difference was about 200 in left wheel to 600+ in the right one.
We should try change the sensor orientation to vertical & position to the center of wheel.

**Comment by MichaelACosta** [comment]
This difference occurs because we use a single arduino to capture the data from the two sensors and move the robot. Due to the high complexity of the sensors used in the design, we will use two arduinos.

With this, we must pass a sensor for an arduino along with the gyroscope and the other sensor to keep in the current arduino with the command of the wheels.

Before we do a test with the two sensors in the current arduino, just use the sensor code and push the robot, do not use the movement code in this test, compare the two sensors.
